runtime: python312  # Ensure you are using the correct Python version
entrypoint: gunicorn -b :$PORT core.wsgi

instance_class: F2  # Adjust based on your needs

service: default
service_account: ai-fullstack-portfolio@appspot.gserviceaccount.com

env_variables:
  GAE_SERVICE_ACCOUNT: "ai-fullstack-portfolio@appspot.gserviceaccount.com"
  GOOGLE_APPLICATION_CREDENTIALS: "/workspace/key.json"
  DJANGO_SETTINGS_MODULE: "core.settings"
  DEBUG: "False"

  # 🔒 Database credentials should be handled securely
  DB_NAME: "Portfolio"
  DB_USER: "portfolioApp"
  DB_PASSWORD: "JuanPaco1993#"  # Removed hardcoded password
  DB_HOST: "217.196.48.82"
  DB_PORT: "3306"
  DATABASE_URL: "mysql://portfolioApp:JuanPaco1993%23@217.196.48.82:3306/Portfolio"

  # Google Cloud Storage
  GS_BUCKET_NAME: "ai-fullstack-portfolio.appspot.com"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
  - url: /static
    static_files: static/*
    upload: static/*

  - url: /(.*)
    script: auto
