runtime: python312  # Change to your Python version (e.g., python311)
entrypoint: gunicorn -b :$PORT core.wsgi


instance_class: F2  # Choose an instance class based on your needs

service: default

env_variables:
  DJANGO_SETTINGS_MODULE: "core.settings"
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DEBUG: "False"



automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
  - url: /static
    static_dir: staticfiles
  - url: /.*
    script: auto
