# Generated by Django 6.0.1 on 2026-01-28 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSessionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(choices=[('NQ=F', 'E-mini Nasdaq-100'), ('ES=F', 'E-mini S&P 500'), ('RTY=F', 'E-mini Russell 2000'), ('YM=F', 'E-mini Dow Jones')], max_length=10)),
                ('session_date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overnight_high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('overnight_low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('prior_close', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('change_points', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trading_market_sessions',
                'ordering': ['-session_date'],
                'indexes': [models.Index(fields=['instrument', '-session_date'], name='trading_mar_instrum_add6e2_idx')],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'session_date'), name='unique_session_per_day')],
            },
        ),
        migrations.CreateModel(
            name='PriceLevelModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(choices=[('NQ=F', 'E-mini Nasdaq-100'), ('ES=F', 'E-mini S&P 500'), ('RTY=F', 'E-mini Russell 2000'), ('YM=F', 'E-mini Dow Jones')], max_length=10)),
                ('level_type', models.CharField(choices=[('prior_high', 'Prior Day High'), ('prior_low', 'Prior Day Low'), ('prior_close', 'Prior Day Close'), ('overnight_high', 'Overnight High'), ('overnight_low', 'Overnight Low'), ('weekly_open', 'Weekly Open'), ('weekly_high', 'Weekly High'), ('weekly_low', 'Weekly Low'), ('monthly_high', 'Monthly High'), ('monthly_low', 'Monthly Low')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('session_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trading_price_levels',
                'ordering': ['-session_date', 'level_type'],
                'indexes': [models.Index(fields=['instrument', '-session_date'], name='trading_pri_instrum_cf8f4c_idx'), models.Index(fields=['instrument', 'level_type'], name='trading_pri_instrum_ef04b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklySessionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(choices=[('NQ=F', 'E-mini Nasdaq-100'), ('ES=F', 'E-mini S&P 500'), ('RTY=F', 'E-mini Russell 2000'), ('YM=F', 'E-mini Dow Jones')], max_length=10)),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_points', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('total_volume', models.BigIntegerField(default=0)),
                ('trading_days', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trading_weekly_sessions',
                'ordering': ['-week_start_date'],
                'indexes': [models.Index(fields=['instrument', '-week_start_date'], name='trading_wee_instrum_2bd6d6_idx')],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'week_start_date'), name='unique_weekly_session_per_week')],
            },
        ),
        migrations.CreateModel(
            name='TradingPostModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(choices=[('NQ=F', 'E-mini Nasdaq-100'), ('ES=F', 'E-mini S&P 500'), ('RTY=F', 'E-mini Russell 2000'), ('YM=F', 'E-mini Dow Jones')], max_length=10)),
                ('post_type', models.CharField(choices=[('pre_market', 'Pre-Market Analysis'), ('post_market', 'Session Recap'), ('weekly_recap', 'Weekly Recap')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('session_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('market_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_posts', to='trading.marketsessionmodel')),
                ('weekly_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_posts', to='trading.weeklysessionmodel')),
            ],
            options={
                'db_table': 'trading_posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingPostPriceLevelModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_trading_posts', to='trading.pricelevelmodel')),
                ('trading_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_price_levels', to='trading.tradingpostmodel')),
            ],
            options={
                'db_table': 'trading_post_price_levels',
                'constraints': [models.UniqueConstraint(fields=('trading_post', 'price_level'), name='unique_post_level_relationship')],
            },
        ),
        migrations.AddIndex(
            model_name='tradingpostmodel',
            index=models.Index(fields=['slug'], name='trading_pos_slug_72ae8a_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingpostmodel',
            index=models.Index(fields=['instrument', 'post_type'], name='trading_pos_instrum_cb4947_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingpostmodel',
            index=models.Index(fields=['status', '-published_at'], name='trading_pos_status_83c114_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingpostmodel',
            index=models.Index(fields=['session_date'], name='trading_pos_session_d22c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingpostmodel',
            index=models.Index(fields=['scheduled_for'], name='trading_pos_schedul_c43d0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='tradingpostmodel',
            constraint=models.UniqueConstraint(fields=('instrument', 'post_type', 'session_date'), name='unique_trading_post_per_session'),
        ),
    ]
