# Generated by Django 6.0.1 on 2026-01-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpostmodel',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
