# Generated by Django 6.0.1 on 2026-01-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_add_structured_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntradayBarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('NQ=F', 'E-mini Nasdaq-100'), ('ES=F', 'E-mini S&P 500'), ('RTY=F', 'E-mini Russell 2000'), ('YM=F', 'E-mini Dow Jones')], max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('session_date', models.DateField()),
                ('session_type', models.CharField(choices=[('overnight', 'Overnight Session (6PM-9:30AM ET)'), ('rth', 'Regular Trading Hours (9:30AM-4PM ET)')], default='rth', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trading_intraday_bars',
                'ordering': ['instrument', 'timestamp'],
                'indexes': [models.Index(fields=['instrument', 'session_date'], name='trading_int_instrum_34d7df_idx'), models.Index(fields=['instrument', 'session_date', 'session_type'], name='trading_int_instrum_bc1c4f_idx'), models.Index(fields=['instrument', 'timestamp'], name='trading_int_instrum_29d63b_idx')],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'timestamp'), name='unique_bar_per_instrument_timestamp')],
            },
        ),
    ]
