# Generated by Django 6.0.5 on 2026-05-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_type',
            field=models.CharField(choices=[('deliverable.approved', 'Deliverable Approved'), ('metric.threshold_crossed', 'Metric Threshold Crossed'), ('invoice.overdue', 'Invoice Overdue'), ('file.uploaded', 'File Uploaded')], db_index=True, max_length=40),
        ),
    ]
