# Generated by Django 6.0.5 on 2026-05-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0002_make_activityevent_actor_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
