"""Trading post reviewer service.

Reviews AI-generated trading content for accuracy, compliance, and quality.
Uses a separate model to validate content before publication.
"""
import json
import logging
import time
from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Tuple

from django.conf import settings
from django.utils import timezone

from apps.trading.domain.value_objects import Instrument, PostType


logger = logging.getLogger(__name__)


@dataclass
class ReviewResult:
    """Result of trading post review."""
    approved: bool
    quality_score: float  # 0-10 scale
    compliance_passed: bool  # No trading recommendations
    accuracy_score: float  # Price levels correctly referenced
    improvements: List[str]  # Suggested improvements
    issues: List[str]  # Critical issues found
    revised_content: str  # Polished content if approved
    revised_title: str
    revised_meta_description: str
    input_tokens: int = 0
    output_tokens: int = 0
    duration_seconds: float = 0.0
    error_message: str = ""


@dataclass
class ReviewLog:
    """Log entry for content review attempts."""
    post_type: PostType
    instrument: Instrument
    model_used: str
    quality_score: float
    compliance_passed: bool
    approved: bool
    input_tokens: int
    output_tokens: int
    duration_seconds: float
    issues_found: int
    created_at: datetime = field(default_factory=timezone.now)


class TradingPostReviewerService:
    """Service for reviewing trading blog post content.
    
    Uses a fast model (gpt-5-mini) to review content generated by
    the reasoning model (o3-mini), checking for:
    - Accuracy of price level references
    - Compliance (no trading recommendations)
    - Professional tone and clarity
    - Overall content quality
    
    Note: Disclaimer is added mechanically in the template, not checked here.
    """
    
    # gpt-5-mini for fast, accurate review
    DEFAULT_MODEL = "gpt-5-mini"
    
    # Thresholds for auto-approval
    QUALITY_THRESHOLD = 7.0
    ACCURACY_THRESHOLD = 8.0
    
    def __init__(
        self,
        openai_api_key: str | None = None,
        model: str | None = None,
    ) -> None:
        """Initialize the reviewer service.
        
        Args:
            openai_api_key: OpenAI API key (defaults to settings.OPENAI_API_KEY)
            model: Model to use for review (defaults to gpt-5-mini)
        """
        self.openai_api_key = openai_api_key or getattr(settings, 'OPENAI_API_KEY', '')
        self.model = model or self.DEFAULT_MODEL
        self._client = None
    
    @property
    def client(self):
        """Lazy load OpenAI client."""
        if self._client is None:
            from openai import OpenAI
            self._client = OpenAI(api_key=self.openai_api_key)
        return self._client
    
    def review_content(
        self,
        title: str,
        content: str,
        meta_description: str,
        instrument: Instrument,
        post_type: PostType,
        price_levels_mentioned: List[str] | None = None,
        intraday_data_provided: bool = False,
        intraday_summary: str | None = None,
    ) -> Tuple[ReviewResult, ReviewLog]:
        """Review generated trading content for quality and compliance.
        
        Args:
            title: Post title
            content: Post content in Markdown
            meta_description: SEO meta description
            instrument: Futures instrument (NQ, ES, etc.)
            post_type: Type of post (PRE_MARKET, POST_MARKET, WEEKLY_RECAP)
            price_levels_mentioned: Optional list of price levels that should appear
            intraday_data_provided: Whether intraday bar data was provided to generator
            intraday_summary: Summary of intraday data for verification (timestamps, etc.)
            
        Returns:
            Tuple of (ReviewResult, ReviewLog)
        """
        start_time = time.time()
        
        prompt = self._build_review_prompt(
            title=title,
            content=content,
            meta_description=meta_description,
            instrument=instrument,
            post_type=post_type,
            price_levels_mentioned=price_levels_mentioned,
            intraday_data_provided=intraday_data_provided,
            intraday_summary=intraday_summary,
        )
        
        try:
            # Build request - some models (gpt-5-mini) don't support temperature
            request_params = {
                "model": self.model,
                "messages": [
                    {"role": "system", "content": self._get_system_prompt()},
                    {"role": "user", "content": prompt},
                ],
                "max_completion_tokens": 4000,
                "response_format": {"type": "json_object"},
            }
            
            # Only add temperature for models that support it
            if not self.model.endswith("-mini"):
                request_params["temperature"] = 0.3
            
            response = self.client.chat.completions.create(**request_params)
            
            duration = time.time() - start_time
            raw_response = response.choices[0].message.content or "{}"
            
            # Parse the JSON response
            review_data = json.loads(raw_response)
            
            # Extract token usage
            usage = response.usage
            input_tokens = usage.prompt_tokens if usage else 0
            output_tokens = usage.completion_tokens if usage else 0
            
            # Build result
            quality_score = float(review_data.get('quality_score', 5.0))
            accuracy_score = float(review_data.get('accuracy_score', 5.0))
            compliance_passed = review_data.get('compliance_passed', False)
            issues = review_data.get('issues', [])
            
            # Identify critical issues (blockers for publication)
            # These types are always blockers:
            blocking_types = {'fabrication', 'compliance', 'accuracy'}
            
            critical_issues = []
            for issue in issues:
                if isinstance(issue, dict):
                    issue_type = issue.get('type', '').lower()
                    if issue_type in blocking_types:
                        critical_issues.append(issue)
                elif isinstance(issue, str):
                    # Legacy format - check for blocking keywords
                    i_lower = issue.lower()
                    blocking_keywords = [
                        'fabricat', 'invented', 'assumed', 'hallucin',  # Fabrication
                        'recommend', 'buy', 'sell', 'prediction', 'predict',  # Compliance
                        'incorrect', 'wrong', 'error', 'mismatch', 'inaccurate',  # Accuracy
                        'likely', 'probably', 'may have', 'suggests', 'indicates',  # Speculation
                        'buyers', 'sellers', 'bulls', 'bears', 'sentiment',  # No order flow
                    ]
                    if any(kw in i_lower for kw in blocking_keywords):
                        critical_issues.append(issue)
            
            # Determine approval - block on any critical issue
            approved = (
                quality_score >= self.QUALITY_THRESHOLD
                and accuracy_score >= self.ACCURACY_THRESHOLD
                and compliance_passed
                and len(critical_issues) == 0
            )
            
            result = ReviewResult(
                approved=approved,
                quality_score=quality_score,
                compliance_passed=compliance_passed,
                accuracy_score=accuracy_score,
                improvements=review_data.get('improvements', []),
                issues=issues,
                revised_content=review_data.get('revised_content', content),
                revised_title=review_data.get('revised_title', title),
                revised_meta_description=review_data.get(
                    'revised_meta_description', meta_description
                ),
                input_tokens=input_tokens,
                output_tokens=output_tokens,
                duration_seconds=duration,
            )
            
            log = ReviewLog(
                post_type=post_type,
                instrument=instrument,
                model_used=self.model,
                quality_score=quality_score,
                compliance_passed=compliance_passed,
                approved=approved,
                input_tokens=input_tokens,
                output_tokens=output_tokens,
                duration_seconds=duration,
                issues_found=len(issues),
            )
            
            logger.info(
                f"Reviewed {post_type.value} post for {instrument.short_name}: "
                f"score={quality_score:.1f}, approved={approved}"
            )
            
            return result, log
            
        except json.JSONDecodeError as e:
            duration = time.time() - start_time
            logger.error(f"Failed to parse review response: {e}")
            
            result = ReviewResult(
                approved=False,
                quality_score=0.0,
                compliance_passed=False,
                accuracy_score=0.0,
                improvements=[],
                issues=["Failed to parse review response"],
                revised_content=content,
                revised_title=title,
                revised_meta_description=meta_description,
                duration_seconds=duration,
                error_message=str(e),
            )
            
            log = ReviewLog(
                post_type=post_type,
                instrument=instrument,
                model_used=self.model,
                quality_score=0.0,
                compliance_passed=False,
                approved=False,
                input_tokens=0,
                output_tokens=0,
                duration_seconds=duration,
                issues_found=1,
            )
            
            return result, log
            
        except Exception as e:
            duration = time.time() - start_time
            logger.error(f"Review failed: {e}")
            
            result = ReviewResult(
                approved=False,
                quality_score=0.0,
                compliance_passed=False,
                accuracy_score=0.0,
                improvements=[],
                issues=[str(e)],
                revised_content=content,
                revised_title=title,
                revised_meta_description=meta_description,
                duration_seconds=duration,
                error_message=str(e),
            )
            
            log = ReviewLog(
                post_type=post_type,
                instrument=instrument,
                model_used=self.model,
                quality_score=0.0,
                compliance_passed=False,
                approved=False,
                input_tokens=0,
                output_tokens=0,
                duration_seconds=duration,
                issues_found=1,
            )
            
            return result, log
    
    def _get_system_prompt(self) -> str:
        """Get the system prompt for content review."""
        return """You are a financial content compliance reviewer for a futures trading blog.

YOUR ROLE:
Review trading data reports for ACCURACY, COMPLIANCE, and ZERO FABRICATION.
You are the second model in a two-model pipeline - your job is to catch
any fabricated, assumed, or invented content.

FABRICATION DETECTION (CRITICAL - REJECT IF FOUND):
1. Narrative about intraday price action WITHOUT intraday timing data provided
2. Claims about "buyers", "sellers", "bulls", "bears" without order flow data
3. Statements about market "sentiment", "conviction", or "confidence"
4. Phrases like "likely", "probably", "may have", "suggests", "indicates"
5. Explanations of WHY price moved (causation without evidence)
6. Any number that cannot be traced to provided data
7. Descriptions of "support" or "resistance" behavior without tick data

COMPLIANCE REQUIREMENTS (CRITICAL):
1. NO trading recommendations (buy, sell, long, short signals)
2. NO specific price targets or predictions
3. NO promises of returns or profit potential
4. NO "watch for", "look for", "expect" language
5. Content must be pure data reporting only

Note: A disclaimer is added automatically by the system - do not check for one.

ACCURACY CHECKS:
1. All prices must match the source data exactly
2. All calculations (range, change, percentages) must be mathematically correct
3. Dates must match the content context
4. If intraday timing is mentioned, verify intraday data was provided

QUALITY STANDARDS:
1. Professional, neutral tone (not "analytical" - just reporting)
2. Clear and concise data presentation
3. Proper Markdown formatting
4. No AI-typical phrases (delve, crucial, landscape, dive into, navigate, etc.)
5. No subjective adjectives (significant, notable, important, key)

RESPONSE FORMAT (JSON):
{
    "quality_score": 8.5,
    "accuracy_score": 9.0,
    "compliance_passed": true,
    "issues": [
        {"type": "fabrication", "text": "Content describes 'buyers stepping in' without order flow data"},
        {"type": "compliance", "text": "Contains prediction 'price may test resistance'"}
    ],
    "improvements": ["Minor formatting fix"],
    "revised_title": "Factual title",
    "revised_content": "Full content with fabrications removed",
    "revised_meta_description": "Factual meta"
}

Issue types:
- "fabrication": Invented/assumed information (BLOCKER)
- "compliance": Trading advice or prediction (BLOCKER)
- "accuracy": Mathematical or data error (BLOCKER)
- "quality": Minor quality issue (NOT A BLOCKER)

If you find fabrication, compliance, or accuracy issues, they MUST be listed
and the content should be revised to remove them. Set appropriate scores low.
"""
    
    def _build_review_prompt(
        self,
        title: str,
        content: str,
        meta_description: str,
        instrument: Instrument,
        post_type: PostType,
        price_levels_mentioned: List[str] | None = None,
        intraday_data_provided: bool = False,
        intraday_summary: str | None = None,
    ) -> str:
        """Build the review prompt with content to check."""
        levels_section = ""
        if price_levels_mentioned:
            levels_section = f"""
PRICE LEVELS FROM SOURCE DATA:
{chr(10).join(f'- {level}' for level in price_levels_mentioned)}

Verify these levels appear accurately. Flag any prices NOT in this list.
"""
        
        # Check if intraday data was likely provided (look for timing in content)
        has_intraday_timing = any(
            phrase in content.lower()
            for phrase in ['am et', 'pm et', ':30', ':00', 'opening 30', 'final hour']
        )
        
        intraday_note = ""
        if has_intraday_timing:
            if intraday_data_provided:
                # Intraday data WAS provided - timing is legitimate
                intraday_note = """
NOTE: Intraday bar data (1-minute bars) was provided to the content generator.
Intraday timing references are LEGITIMATE and should NOT be flagged as fabrication.
"""
                if intraday_summary:
                    intraday_note += f"""
INTRADAY DATA SUMMARY (for verification):
{intraday_summary}
"""
            else:
                # No intraday data was provided - timing may be fabricated
                intraday_note = """
NOTE: Content mentions intraday timing. Verify this is backed by data.
If intraday progression data was not explicitly provided, these timings
may be FABRICATED and should be flagged.
"""
        
        return f"""Review this {post_type.display_name} for {instrument.display_name} ({instrument.short_name}):

---TITLE---
{title}

---META_DESCRIPTION---
{meta_description}

---CONTENT---
{content}

---END CONTENT---
{levels_section}{intraday_note}
CRITICAL CHECKS:
1. FABRICATION: Does content describe things not provable from OHLC data?
   - Intraday timing without intraday data = FABRICATION
   - Buyer/seller behavior without order flow = FABRICATION  
   - "Support held" or "resistance rejected" without tick data = FABRICATION
   - Phrases like "likely", "suggests", "indicates" = SPECULATION

2. COMPLIANCE: Any trading advice or predictions?
   - "Watch for", "look for", "expect" = VIOLATION
   - Price targets or directional predictions = VIOLATION

3. ACCURACY: Do all numbers match and calculate correctly?

Respond with JSON containing your review. Use issue type "fabrication",
"compliance", or "accuracy" for blocking issues.
"""


def get_trading_post_reviewer() -> TradingPostReviewerService:
    """Factory function for TradingPostReviewerService.
    
    Returns:
        Configured TradingPostReviewerService instance
    """
    return TradingPostReviewerService()
