# Generated by Django 6.0.1 on 2026-01-28 01:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIdeaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=300)),
                ('keywords', models.JSONField(default=list)),
                ('source', models.CharField(choices=[('trends', 'Google Trends'), ('manual', 'Manual Entry'), ('ai_suggested', 'AI Suggested')], default='ai_suggested', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('expertise_area', models.CharField(max_length=100)),
                ('trend_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_idea', to='blog.blogpostmodel')),
            ],
            options={
                'db_table': 'blog_ideas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentGenerationLogModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('idea_generation', 'Idea Generation'), ('content_creation', 'Content Creation'), ('proofreading', 'Proofreading'), ('publishing', 'Publishing')], max_length=30)),
                ('model_used', models.CharField(max_length=50)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('success', models.BooleanField(default=True)),
                ('output_preview', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to='blog.blogideamodel')),
            ],
            options={
                'db_table': 'content_generation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blogideamodel',
            index=models.Index(fields=['status', '-created_at'], name='blog_ideas_status_8116b1_idx'),
        ),
        migrations.AddIndex(
            model_name='blogideamodel',
            index=models.Index(fields=['expertise_area'], name='blog_ideas_experti_31811b_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgenerationlogmodel',
            index=models.Index(fields=['idea', 'stage'], name='content_gen_idea_id_cd461a_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgenerationlogmodel',
            index=models.Index(fields=['created_at'], name='content_gen_created_06f8a9_idx'),
        ),
    ]
