# Generated by Django 4.2.18 on 2025-02-06 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiservice",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_services",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
