"""Post-market recap prompt for trading blog posts.

Generates end-of-day recap content with rich session narrative.
"""
from dataclasses import dataclass, field
from datetime import date
from decimal import Decimal
from typing import List, Optional, TYPE_CHECKING

from apps.trading.domain.entities import MarketSession, PriceLevel
from apps.trading.domain.value_objects import Instrument, LevelType, Price

if TYPE_CHECKING:
    from apps.trading.application.intraday_analysis import SessionProgression


@dataclass
class PostMarketContext:
    """Context data for post-market recap generation.
    
    Contains the completed session data and prior levels for analysis.
    """
    instrument: Instrument
    session_date: date
    current_session: MarketSession
    prior_levels: List[PriceLevel]  # Levels from pre-market that day
    weekly_high: Price | None
    weekly_low: Price | None
    monthly_high: Price | None
    monthly_low: Price | None
    # Optional intraday progression from 1-minute bar analysis
    intraday_progression: Optional["SessionProgression"] = None


class PostMarketPromptBuilder:
    """Builds AI prompts for post-market recap posts.
    
    Creates structured prompts for analyzing how the session played out
    relative to the pre-market levels identified earlier.
    
    Note: Disclaimer is rendered mechanically in the template,
    not generated by the AI model.
    """
    
    def build_prompt(self, context: PostMarketContext) -> str:
        """Build the complete prompt for post-market recap generation.
        
        Args:
            context: PostMarketContext with completed session data
            
        Returns:
            Formatted prompt string for AI model
        """
        session_summary = self._build_session_summary(context)
        levels_analysis = self._build_levels_analysis(context)
        context_summary = self._build_context_summary(context)
        intraday_context = self._build_intraday_context(context)
        
        # Include intraday section only if we have the data
        intraday_section = ""
        if intraday_context:
            intraday_section = f"""
INTRADAY SESSION PROGRESSION (from 1-minute bar analysis):
{intraday_context}
"""
        
        prompt = f"""Generate a post-market session recap blog post for {context.instrument.display_name} ({context.instrument.short_name}) futures.

SESSION DATE: {context.session_date.strftime('%A, %B %d, %Y')}

SESSION DATA:
{session_summary}
{intraday_section}
HOW PRE-MARKET LEVELS PLAYED OUT:
{levels_analysis}

BROADER CONTEXT:
{context_summary}

═══════════════════════════════════════════════════════════════════════════════
YOUR TASK: Write an engaging, professional post-market recap that reads like it 
was written by an experienced futures trader—not a data dump.
═══════════════════════════════════════════════════════════════════════════════

WRITING STYLE GUIDELINES:

1. TELL THE SESSION'S STORY using the data provided:
   - How did the session unfold? Where did it start, what happened, where did it end?
   - Use the timing data (when highs/lows occurred) to create narrative flow
   - Connect the phases: opening drive → mid-session → close

2. MAKE OBSERVATIONS from the data (this is NOT fabrication):
   ✓ "The low was established in the first 10 minutes and held for the remainder of the session"
   ✓ "Price spent the majority of the session above yesterday's close"
   ✓ "Volume was front-loaded, with 60% occurring before noon"
   ✓ "The session closed in the upper quarter of the day's range"
   These are FACTS derived from the data—use them to add depth.
   (Only reference overnight levels if they are explicitly provided in the data.)

3. DESCRIBE PRICE BEHAVIOR in professional terms:
   ✓ "Price rotated within a 40-point range" (if range was 40 pts)
   ✓ "The session saw a measured advance from the opening low"
   ✓ "Price faded from the morning highs into the close"
   Avoid: "Bulls took control" / "Sellers stepped in" (you can't see order flow)

4. PROVIDE CONTEXT that helps readers understand:
   - Where today fits within the week's range
   - How today's action relates to overnight levels
   - Whether key reference levels were tested or respected

5. WRITE FLOWING PROSE, not just bullet points:
   INSTEAD OF: "• Session low: 5080.25 at 9:35 AM"
   WRITE: "The session established its low of 5080.25 within the first five minutes 
   of trade. This level held throughout the day, with price never returning to 
   test it."

WHAT TO AVOID:
- Making predictions or forecasts
- Describing trader psychology ("fear", "greed", "panic")
- Attributing moves to news or events unless specifically provided
- Using hollow phrases like "key level" without explaining why it matters
- Pure data tables without narrative context

═══════════════════════════════════════════════════════════════════════════════
BANNED AI PHRASES — DO NOT USE THESE UNDER ANY CIRCUMSTANCES:
═══════════════════════════════════════════════════════════════════════════════
The following words and phrases are PROHIBITED. Using them will cause rejection:

BANNED VERBS/PHRASES:
- "delve", "navigate", "landscape", "crucial", "notably"  
- "underscores", "underscoring", "highlighting", "showcasing"
- "remains to be seen", "time will tell", "only time will tell"
- "traders will watch", "traders will monitor", "market participants"
- "respectable" (as in "respectable gain")
- "marched higher/lower", "marched steadily"
- "controlled the tape", "buyers/sellers controlled"
- "the tone changed", "tone shifted"
- "stripping away", "peeling back"
- "proved durable", "proved resilient"  
- "illustrating how", "demonstrating that"
- "reminding traders", "serves as a reminder"
- "press their advantage", "press the advantage"
- "remained constructive", "constructive price action"
- "liquidity followed the move"
- "kept buyers/sellers in control", "in control"
- "surrendering", "surrendered"
- "reinforcing", "reinforced"
- "stepped back in", "stepped in"
- "flipped the script", "script"
- "a steady drip of", "drip"
- "selling/buying pressure"
- "upward/downward bias"
- "momentum continued", "momentum carried"
- "two-way rotation"

BANNED SENTENCE STRUCTURES:
- "...yet the contract couldn't..." (anthropomorphizing the contract)
- "...only to see..." (dramatic foreshadowing)
- "...with the contract still..." (narrative padding)
- "...a clear sign that..." (interpretation disguised as fact)

BANNED PUNCTUATION:
- Em-dashes (—) are PROHIBITED. Do not use them at all.
  ✗ "The session low—established at 9:39 AM—held for the day"
  ✓ "The session low of 6,988.25 was established at 9:39 AM. It held for the day."
  Use periods to create separate sentences instead of em-dashes.

INSTEAD, WRITE PLAINLY:
✗ "Buyers controlled the tape through the late morning"
✓ "Price moved higher through the late morning"

✗ "The tone changed in the final 60 minutes"  
✓ "The final hour saw price fade from session highs"

✗ "This level proved durable—price never returned to test it"
✓ "Price did not return to this level for the rest of the session"

✗ "...a clear sign that sellers could not press their advantage"
✓ "The gap remained unfilled"

Write like a veteran trader dictating notes into a recorder after the close—
terse, factual, no flourishes. Every word should earn its place.
═══════════════════════════════════════════════════════════════════════════════
CRITICAL DATA INTEGRITY RULE — READ CAREFULLY:
═══════════════════════════════════════════════════════════════════════════════
You may ONLY cite prices, times, and percentages that appear VERBATIM in the data 
above. This is non-negotiable.

If there is NO INTRADAY PROGRESSION section above, you MUST NOT:
  ✗ Mention specific times (e.g., "at 9:39 a.m.", "by 11:41 a.m.")
  ✗ Describe intraday price levels other than Open/High/Low/Close
  ✗ State volume distributions (e.g., "48% before noon")
  ✗ Describe price action phases (e.g., "dipped to 6,992 then rallied")

If no intraday data is provided, write a GENERAL narrative using ONLY:
  ✓ Open, High, Low, Close from the SESSION DATA
  ✓ Prior close and calculated change
  ✓ Weekly/monthly context from BROADER CONTEXT
  ✓ Descriptive statements like "the session traded within an 84-point range"

DO NOT FABRICATE INTRADAY DETAILS. If you cannot verify a number in the data 
provided, do not include it.
═══════════════════════════════════════════════════════════════════════════════

POST STRUCTURE (use these exact headings):

## Session Overview
Open with 2-3 sentences that capture the essence of the session. Then include
the data table. Follow with 1-2 paragraphs that put the numbers in context.

| Metric | Value |
|--------|-------|
| Open | [price] |
| High | [price] |
| Low | [price] |  
| Close | [price] |
| Range | [points] |
| Change | [+/- points and %] |

## How the Session Unfolded
Tell the story of the session chronologically using the intraday progression data.
Describe the opening action, mid-session behavior, and closing dynamics.
Use specific times and prices from the data. This should read like market commentary.

## Reference Levels
Discuss how the pre-identified levels performed. Which were tested? Which held?
Which remained untouched? Frame this as useful context, not "predictions came true."

## Looking Ahead
List the levels that carry forward as reference points for tomorrow. Keep this
factual—state what the levels are, don't predict what will happen.

TARGET LENGTH: 500-700 words of substantive content.

Note: Disclaimer is added automatically by the system.

FORMAT YOUR RESPONSE AS:
---TITLE---
[Compelling title, e.g., "ES Futures Recap: Early Low Holds as Price Grinds Higher"]

---CONTENT---
[Full Markdown content with rich narrative]

---META_DESCRIPTION---
[150-160 char description that captures the session's character]
"""
        return prompt
    
    def _build_session_summary(self, context: PostMarketContext) -> str:
        """Build summary of session statistics."""
        session = context.current_session
        
        parts = [
            f"Open: {session.open_price}",
            f"High: {session.high_price}",
            f"Low: {session.low_price}",
            f"Close: {session.close_price}",
        ]
        
        # Calculate session range
        session_range = float(session.high_price.value) - float(session.low_price.value)
        parts.append(f"Range: {session_range:.2f} points")
        
        # Include prior close and calculate change
        if session.prior_close:
            parts.append(f"Prior Close: {session.prior_close}")
            change_points = float(session.close_price.value) - float(session.prior_close.value)
            change_pct = (change_points / float(session.prior_close.value)) * 100
            sign = "+" if change_points >= 0 else ""
            parts.append(
                f"Change (vs Prior Close): {sign}{change_points:.2f} points "
                f"({sign}{change_pct:.2f}%)"
            )
        
        if session.volume > 0:
            parts.append(f"Volume: {session.volume:,}")
        
        return "\n".join(f"- {p}" for p in parts)
    
    def _build_levels_analysis(self, context: PostMarketContext) -> str:
        """Build analysis of how pre-market levels performed."""
        session = context.current_session
        session_high = float(session.high_price.value)
        session_low = float(session.low_price.value)
        session_close = float(session.close_price.value)
        
        analysis_points = []
        
        for level in context.prior_levels:
            level_price = float(level.price.value)
            level_name = level.level_type.display_name
            
            # Determine how price interacted with this level
            if session_low <= level_price <= session_high:
                # Level was tested
                if session_close > level_price:
                    analysis_points.append(
                        f"- {level_name} ({level.price}): Tested and price closed above"
                    )
                elif session_close < level_price:
                    analysis_points.append(
                        f"- {level_name} ({level.price}): Tested and price closed below"
                    )
                else:
                    analysis_points.append(
                        f"- {level_name} ({level.price}): Tested, closed near this level"
                    )
            elif session_high < level_price:
                # Price stayed below this level
                analysis_points.append(
                    f"- {level_name} ({level.price}): Price traded below, never tested"
                )
            elif session_low > level_price:
                # Price stayed above this level
                analysis_points.append(
                    f"- {level_name} ({level.price}): Price traded above, held as support"
                )
        
        if not analysis_points:
            return "No pre-market levels were provided for analysis."
        
        return "\n".join(analysis_points)
    
    def _build_intraday_context(self, context: PostMarketContext) -> str:
        """Build intraday session progression context from 1-minute bar analysis.
        
        Returns an empty string if intraday data is not available.
        """
        if not context.intraday_progression:
            return ""
        
        return context.intraday_progression.to_prompt_context()
    
    def _build_context_summary(self, context: PostMarketContext) -> str:
        """Build broader market context summary."""
        parts = []
        session = context.current_session
        session_close = float(session.close_price.value)
        
        if context.weekly_high and context.weekly_low:
            weekly_high = float(context.weekly_high.value)
            weekly_low = float(context.weekly_low.value)
            
            if session_close >= weekly_high * 0.995:  # Within 0.5% of weekly high
                parts.append("Session closed near weekly highs.")
            elif session_close <= weekly_low * 1.005:  # Within 0.5% of weekly low
                parts.append("Session closed near weekly lows.")
            
            weekly_range = weekly_high - weekly_low
            parts.append(f"Weekly range: {weekly_range:.2f} points")
        
        if context.monthly_high and context.monthly_low:
            monthly_high = float(context.monthly_high.value)
            monthly_low = float(context.monthly_low.value)
            monthly_range = monthly_high - monthly_low
            
            # Position within monthly range
            if monthly_range > 0:
                position_pct = ((session_close - monthly_low) / monthly_range) * 100
                if position_pct > 80:
                    parts.append(f"Trading in upper portion of monthly range ({position_pct:.0f}%).")
                elif position_pct < 20:
                    parts.append(f"Trading in lower portion of monthly range ({position_pct:.0f}%).")
                else:
                    parts.append(f"Trading mid-range for the month ({position_pct:.0f}%).")
        
        return " ".join(parts) if parts else "Additional context not available."
    
    def get_system_prompt(self) -> str:
        """Get the system prompt for post-market content generation."""
        return """You are a professional futures market analyst writing daily recaps for a trading blog. Your readers are active futures traders who want substantive analysis, not raw data dumps.

YOUR VOICE:
- Write like an experienced trader explaining what happened to a colleague
- Professional but accessible—avoid jargon that doesn't add value  
- Confident and direct, never hedging with "perhaps" or "maybe"
- Observational, not predictive—describe what happened, not what will happen

CORE PRINCIPLES:

1. DATA INTEGRITY IS ABSOLUTE: You may ONLY cite prices, times, and statistics that 
   appear VERBATIM in the user's prompt. If no "INTRADAY SESSION PROGRESSION" section
   exists, you have NO timing data and MUST NOT fabricate any:
   - NO specific times ("at 9:39 a.m.")
   - NO intermediate prices ("dipped to 6,992")
   - NO volume breakdowns ("48% before noon")
   - NO phase descriptions with fabricated details
   
   When intraday data is absent, write a GENERAL narrative using ONLY the OHLCV data
   provided. Say things like "the session traded within an 84-point range" rather than
   inventing minute-by-minute details.

2. NARRATIVE OVER LISTS: Transform data into readable prose. Instead of bullet points,
   write flowing paragraphs that tell the session's story.
   
3. MEANINGFUL OBSERVATIONS: You CAN make observations DERIVABLE from provided data:
   - "The session closed above the open" (verifiable from OHLC)
   - "The range was relatively tight at 84 points" (provided)
   - "The close was in the lower half of the day's range" (calculable from OHLC)
   
   You CANNOT make observations requiring data you don't have:
   - "The low was hit at 9:39 a.m." (requires timing data)
   - "Volume was front-loaded" (requires intraday volume breakdown)
   
4. AVOID FABRICATION: Don't invent:
   - Times or timestamps not explicitly provided
   - Intermediate price levels not in the data
   - Volume distributions not in the data
   - News or catalysts for moves
   - Trader psychology ("fear gripped the market")
   - Order flow you can't see ("buyers stepped in at 5080")
   - Predictions about tomorrow

STRUCTURE YOUR CONTENT:
- Open with a compelling summary that captures the session's character
- Use the data table for reference, then expand with narrative
- If intraday data exists, describe chronologically; if not, describe generally
- Close with forward-looking levels (facts, not predictions)

TARGET: 500-700 words of substantive, professional market commentary."""


def get_postmarket_prompt_builder() -> PostMarketPromptBuilder:
    """Factory function for PostMarketPromptBuilder."""
    return PostMarketPromptBuilder()
