"""Pre-market analysis prompt for trading blog posts.

Generates morning analysis content with key levels and overnight context.
"""
from dataclasses import dataclass, field
from datetime import date
from decimal import Decimal
from typing import List, Optional, TYPE_CHECKING

from apps.trading.domain.entities import MarketSession, PriceLevel
from apps.trading.domain.value_objects import Instrument, LevelType, Price

if TYPE_CHECKING:
    from apps.trading.application.intraday_analysis import SessionProgression, MinuteBar


@dataclass
class PreMarketContext:
    """Context data for pre-market post generation.
    
    Contains all the market data needed to generate a pre-market analysis.
    """
    instrument: Instrument
    session_date: date
    prior_session: MarketSession | None
    overnight_high: Price | None
    overnight_low: Price | None
    weekly_open: Price | None
    weekly_high: Price | None
    weekly_low: Price | None
    monthly_high: Price | None
    monthly_low: Price | None
    price_levels: List[PriceLevel]
    # Prior day's full session progression (raw bars)
    prior_day_progression: Optional["SessionProgression"] = None
    # Current overnight session raw bars (before RTH opens)
    overnight_bars: List["MinuteBar"] = field(default_factory=list)


class PreMarketPromptBuilder:
    """Builds AI prompts for pre-market analysis posts.
    
    Creates structured prompts with market context for generating
    morning analysis content before the regular session opens.
    
    Note: Disclaimer is rendered mechanically in the template,
    not generated by the AI model.
    """
    
    def build_prompt(self, context: PreMarketContext) -> str:
        """Build the complete prompt for pre-market post generation.
        
        Args:
            context: PreMarketContext with all required market data
            
        Returns:
            Formatted prompt string for AI model
        """
        levels_table = self._build_levels_table(context)
        overnight_summary = self._build_overnight_summary(context)
        weekly_context = self._build_weekly_context(context)
        monthly_context = self._build_monthly_context(context)
        prior_day_context = self._build_prior_day_context(context)
        overnight_bars_section = self._build_overnight_bars_section(context)
        
        prompt = f"""Generate a pre-market briefing blog post for {context.instrument.display_name} ({context.instrument.short_name}) futures.

SESSION DATE: {context.session_date.strftime('%A, %B %d, %Y')}

MARKET DATA:
{levels_table}

OVERNIGHT SESSION:
{overnight_summary}

{overnight_bars_section}

PRIOR DAY SESSION:
{prior_day_context}

WEEKLY CONTEXT:
{weekly_context}

MONTHLY CONTEXT:
{monthly_context}

═══════════════════════════════════════════════════════════════════════════════
YOUR TASK: Write an engaging pre-market briefing that sets up the trading day
with context, key levels, and overnight developments—like a morning note from
an institutional trading desk.
═══════════════════════════════════════════════════════════════════════════════

WRITING STYLE GUIDELINES:

1. SET THE STAGE for the trading day:
   - Where are we coming from? (prior session context)
   - What happened overnight? (Globex session narrative)
   - Where do we stand now relative to key reference points?

2. DESCRIBE THE OVERNIGHT SESSION with depth:
   Use the raw bar data to tell the story of overnight trade:
   ✓ "Overnight trade probed lower in the Asian session, finding a low of 5072 
      before recovering through the European open"
   ✓ "The overnight range of 35 points was contained within yesterday's range"
   ✓ "Price held above yesterday's settlement throughout the Globex session"
   The bar data gives you timestamps—use them to describe when things happened.

3. FRAME THE KEY LEVELS with context:
   Don't just list levels—explain what they represent:
   ✓ "Yesterday's high at 5120 marks the upper boundary traders will reference"
   ✓ "The overnight low at 5072 sits just below Friday's settlement"
   ✓ "Weekly range remains 5050 to 5120, with price currently in the upper half"

4. PROVIDE STRUCTURAL CONTEXT:
   - Where is price within the weekly range? (upper third, lower third, middle)
   - How does overnight activity compare to the prior session's range?
   - Are we gapping up/down from the prior close?

5. WRITE PROSE, NOT JUST BULLET POINTS:
   INSTEAD OF: "• Prior High: 5120"
   WRITE: "Yesterday's session peaked at 5120 during the mid-morning hours, a level 
   that will serve as initial upside reference for today's trade."

WHAT TO AVOID:
- Making predictions ("look for support at 5080")
- Describing scenarios ("if price breaks X, then...")  
- Trading advice ("watch for," "look for," "be aware of")
- Using hollow phrases without context
- Em-dashes (—). Use periods to create separate sentences instead.

CRITICAL DATA INTEGRITY RULE:
You may ONLY reference data points that are explicitly provided in the sections above.
Do NOT invent, estimate, or assume any values. If overnight bar data is not provided,
note that and skip the overnight section or state "Overnight data not available." 
Every number you cite must appear in the data provided to you.

POST STRUCTURE (use these exact headings):

## Prior Session Recap
Brief 2-3 sentence summary of yesterday's action. What was the character of 
the session? Where did it close relative to its range?

## Overnight Developments  
Tell the story of the Globex session using the bar data. When did highs/lows 
occur? How does overnight activity set up the regular session? Include the 
overnight range statistics.

## Reference Levels
Present the key levels in a table, then provide a paragraph that puts them
in context. Which levels cluster together? Which represent significant 
structural references?

| Level | Price | Context |
|-------|-------|---------|
| Prior High | [price] | [brief context] |
| Prior Low | [price] | [brief context] |
...etc

## Structural Context
Discuss where current price sits within the bigger picture: weekly range, 
monthly range. Are we extended? Compressed? Near extremes? Be factual but 
provide perspective.

TARGET LENGTH: 500-700 words.

Note: Disclaimer is added automatically by the system.

FORMAT YOUR RESPONSE AS:
---TITLE---
[Compelling title, e.g., "ES Futures Pre-Market: Overnight Holds Above Settlement as 5100 Level Comes Into Focus"]

---CONTENT---
[Full Markdown content with rich narrative]

---META_DESCRIPTION---
[150-160 char description setting up the day]
"""
        return prompt
    
    def _build_levels_table(self, context: PreMarketContext) -> str:
        """Build a markdown table of key price levels."""
        rows = []
        
        # Prior session levels
        if context.prior_session:
            rows.append(
                f"| Prior High | {context.prior_session.high_price} |"
            )
            rows.append(
                f"| Prior Low | {context.prior_session.low_price} |"
            )
            rows.append(
                f"| Prior Close | {context.prior_session.close_price} |"
            )
        
        # Overnight levels
        if context.overnight_high:
            rows.append(f"| Overnight High | {context.overnight_high} |")
        if context.overnight_low:
            rows.append(f"| Overnight Low | {context.overnight_low} |")
        
        # Weekly levels
        if context.weekly_open:
            rows.append(f"| Weekly Open | {context.weekly_open} |")
        if context.weekly_high:
            rows.append(f"| Weekly High | {context.weekly_high} |")
        if context.weekly_low:
            rows.append(f"| Weekly Low | {context.weekly_low} |")
        
        # Monthly levels
        if context.monthly_high:
            rows.append(f"| Monthly High | {context.monthly_high} |")
        if context.monthly_low:
            rows.append(f"| Monthly Low | {context.monthly_low} |")
        
        if not rows:
            return "No price levels available."
        
        table_header = "| Level | Price |\n|-------|-------|"
        return table_header + "\n" + "\n".join(rows)
    
    def _build_overnight_summary(self, context: PreMarketContext) -> str:
        """Build summary of overnight session action."""
        parts = []
        
        if context.overnight_high and context.overnight_low:
            overnight_range = float(context.overnight_high.value) - float(context.overnight_low.value)
            parts.append(
                f"Overnight range: {context.overnight_low} to {context.overnight_high} "
                f"({overnight_range:.2f} points)"
            )
        else:
            parts.append("Overnight data not available.")
        
        if context.prior_session:
            prior_close_val = float(context.prior_session.close_price.value)
            
            if context.overnight_high:
                overnight_high_val = float(context.overnight_high.value)
                if overnight_high_val > prior_close_val:
                    parts.append(
                        f"Overnight high traded above prior close by "
                        f"{overnight_high_val - prior_close_val:.2f} points."
                    )
            
            if context.overnight_low:
                overnight_low_val = float(context.overnight_low.value)
                if overnight_low_val < prior_close_val:
                    parts.append(
                        f"Overnight low traded below prior close by "
                        f"{prior_close_val - overnight_low_val:.2f} points."
                    )
        
        return " ".join(parts) if parts else "Overnight session data not available."
    
    def _build_weekly_context(self, context: PreMarketContext) -> str:
        """Build weekly context summary."""
        parts = []
        
        if context.weekly_high and context.weekly_low:
            weekly_range = float(context.weekly_high.value) - float(context.weekly_low.value)
            parts.append(
                f"This week's range so far: {context.weekly_low} to {context.weekly_high} "
                f"({weekly_range:.2f} points)"
            )
        
        if context.weekly_open:
            parts.append(f"Weekly open: {context.weekly_open}")
            
            if context.prior_session:
                prior_close = float(context.prior_session.close_price.value)
                weekly_open = float(context.weekly_open.value)
                week_change = prior_close - weekly_open
                week_pct = (week_change / weekly_open) * 100
                direction = "up" if week_change > 0 else "down"
                parts.append(
                    f"Week-to-date: {direction} {abs(week_change):.2f} points ({abs(week_pct):.2f}%)"
                )
        
        return " ".join(parts) if parts else "Weekly context not available."
    
    def _build_monthly_context(self, context: PreMarketContext) -> str:
        """Build monthly context summary."""
        if context.monthly_high and context.monthly_low:
            monthly_range = float(context.monthly_high.value) - float(context.monthly_low.value)
            return (
                f"Monthly range: {context.monthly_low} to {context.monthly_high} "
                f"({monthly_range:.2f} points)"
            )
        return "Monthly context not available."
    
    def _build_prior_day_context(self, context: PreMarketContext) -> str:
        """Build prior day session context from progression data."""
        if not context.prior_day_progression:
            return "Prior day intraday progression not available."
        
        prog = context.prior_day_progression
        lines = [
            f"Prior RTH Session ({prog.session_date.strftime('%B %d')}):",
            f"Open: {prog.rth_open} | High: {prog.rth_high} | Low: {prog.rth_low} | Close: {prog.rth_close}",
            f"Session Range: {prog.rth_high - prog.rth_low:.2f} points",
            f"Session Change: {prog.rth_close - prog.rth_open:+.2f} points",
        ]
        
        if prog.session_high_info:
            lines.append(f"Session High at {prog.session_high_info.time_et} ({prog.session_high_info.phase})")
        if prog.session_low_info:
            lines.append(f"Session Low at {prog.session_low_info.time_et} ({prog.session_low_info.phase})")
        
        # Include prior day's RTH bar data (sampled for context)
        if prog.rth_bars:
            lines.append("")
            lines.append(f"Prior Day 1-Minute Bars ({len(prog.rth_bars)} bars):")
            # Sample every 15 min for prior day to keep context manageable
            sampled_bars = prog.rth_bars[::15] if len(prog.rth_bars) > 30 else prog.rth_bars
            for bar in sampled_bars:
                lines.append(bar.to_line())
        
        return "\n".join(lines)
    
    def _build_overnight_bars_section(self, context: PreMarketContext) -> str:
        """Build raw overnight bars section for AI context."""
        if not context.overnight_bars:
            return "RAW OVERNIGHT BARS:\nNo overnight bar data available."
        
        lines = [
            f"RAW OVERNIGHT BARS ({len(context.overnight_bars)} bars from 6:00 PM to now):",
            "Each line: time → O/H/L/C/Volume",
            "This raw data lets you describe authentic overnight price action.",
            ""
        ]
        
        for bar in context.overnight_bars:
            lines.append(bar.to_line())
        
        return "\n".join(lines)
    
    def get_system_prompt(self) -> str:
        """Get the system prompt for pre-market content generation."""
        return """You are a professional futures market analyst writing morning briefings for a trading blog. Your readers are active futures traders preparing for the regular session.

YOUR VOICE:
- Write like a morning note from an institutional trading desk
- Professional, prepared, and contextual
- Focused on setting up the day, not predicting it
- Clear and direct—traders are busy in the morning

CORE PRINCIPLES:

1. DATA INTEGRITY: Every fact must come from the provided data. You have overnight 
   bar data with timestamps—use it to describe when things happened.

2. CONTEXTUAL FRAMING: Don't just list levels—explain what they represent and 
   how they relate to each other. "The overnight low at 5072 sits just 8 points 
   below yesterday's settlement" is more useful than just "Overnight Low: 5072".

3. NARRATIVE STRUCTURE: Tell the story of overnight trade using the bar data:
   - When did the overnight high/low occur? (Asian session? European open?)
   - How does overnight range compare to prior session?
   - Where are we now relative to the overnight range?

4. NO PREDICTIONS OR SCENARIOS: Your job is to set up the context, not predict
   what will happen. Avoid:
   - "Watch for..." or "Look for..."
   - "If price breaks X, then..."
   - "Expect..." or "Likely..."

5. STRUCTURAL PERSPECTIVE: Help readers understand where price sits:
   - Within the weekly range (upper third? lower third?)
   - Relative to the prior session
   - Compared to monthly extremes

STRUCTURE YOUR CONTENT:
- Open with prior session context (set the stage)
- Describe overnight developments with specific timing
- Present levels with meaningful context
- Close with structural perspective

TARGET: 500-700 words of substantive morning preparation."""


def get_premarket_prompt_builder() -> PreMarketPromptBuilder:
    """Factory function for PreMarketPromptBuilder."""
    return PreMarketPromptBuilder()
