"""Weekly recap prompt for trading blog posts.

Generates Saturday weekly summary content with week-over-week analysis.
"""
from dataclasses import dataclass
from datetime import date
from decimal import Decimal
from typing import List

from apps.trading.domain.entities import WeeklySession, MarketSession
from apps.trading.domain.value_objects import Instrument, Price


@dataclass
class WeeklyRecapContext:
    """Context data for weekly recap generation.
    
    Contains the aggregated weekly data and daily breakdown.
    """
    instrument: Instrument
    week_start_date: date
    week_end_date: date
    weekly_session: WeeklySession
    prior_week_close: Price | None
    monthly_high: Price | None
    monthly_low: Price | None


class WeeklyRecapPromptBuilder:
    """Builds AI prompts for weekly recap posts.
    
    Creates structured prompts for comprehensive weekly analysis
    published on Saturdays.
    
    Note: Disclaimer is rendered mechanically in the template,
    not generated by the AI model.
    """
    
    def build_prompt(self, context: WeeklyRecapContext) -> str:
        """Build the complete prompt for weekly recap generation.
        
        Args:
            context: WeeklyRecapContext with aggregated weekly data
            
        Returns:
            Formatted prompt string for AI model
        """
        week_summary = self._build_week_summary(context)
        daily_breakdown = self._build_daily_breakdown(context)
        key_levels = self._build_key_levels(context)
        monthly_context = self._build_monthly_context(context)
        
        week_str = f"{context.week_start_date.strftime('%B %d')} - {context.week_end_date.strftime('%B %d, %Y')}"
        
        prompt = f"""Generate a weekly recap blog post for {context.instrument.display_name} ({context.instrument.short_name}) futures.

WEEK: {week_str}

WEEKLY PERFORMANCE:
{week_summary}

DAILY BREAKDOWN:
{daily_breakdown}

KEY LEVELS FOR THE WEEK:
{key_levels}

MONTHLY CONTEXT:
{monthly_context}

═══════════════════════════════════════════════════════════════════════════════
YOUR TASK: Write an engaging weekly recap that captures the week's trading
character and helps readers understand what happened—like a weekend desk note 
summarizing the week for traders.
═══════════════════════════════════════════════════════════════════════════════

WRITING STYLE GUIDELINES:

1. CAPTURE THE WEEK'S CHARACTER:
   Use the data to describe how the week unfolded:
   ✓ "This was a week of consolidation, with the weekly range compressing to just 45 points"
   ✓ "The week saw a steady grind higher, with each session closing above the prior"
   ✓ "Monday and Tuesday established the week's extremes, with Wed-Fri rotating between them"
   These are OBSERVATIONS from the data—not fabrications.

2. TELL THE STORY DAY BY DAY:
   Don't just list the daily stats—connect them into a narrative:
   ✓ "Monday set the tone with an 80-point range, the widest of the week. The session's 
      low at 5050 would hold as the week's low. Tuesday followed through on Monday's 
      strength, tacking on another 25 points..."
   
3. HIGHLIGHT MEANINGFUL PATTERNS from the data:
   ✓ "Volume was front-loaded: Monday and Tuesday combined for 65% of the week's total"
   ✓ "The week closed near its highs, with Friday's settlement just 8 points below the weekly high"
   ✓ "Three of five sessions closed higher than they opened"

4. PROVIDE STRUCTURAL PERSPECTIVE:
   - How did this week's range compare to recent weeks?
   - Where does the weekly close sit within the monthly range?
   - Did the week expand or contract the monthly range?

5. WRITE FLOWING PARAGRAPHS:
   INSTEAD OF:
   "- Monday: Open 5080, High 5130, Low 5050, Close 5115"
   
   WRITE:
   "Monday opened at 5080 and quickly established the week's low at 5050 within 
   the first hour. From there, price climbed steadily, reaching a session high of 
   5130 before settling at 5115—a 35-point gain that set up the rest of the week."

WHAT TO AVOID:
- Making predictions about next week
- Describing trader psychology or sentiment
- Attributing moves to news unless specifically provided
- Using hollow phrases like "key level" without explaining why
- Just repeating the data table without adding narrative value
- Em-dashes (—). Use periods to create separate sentences instead.

CRITICAL DATA INTEGRITY RULE:
You may ONLY reference data points that are explicitly provided in the DAY-BY-DAY 
and WEEKLY STATISTICS sections above. Do NOT invent, estimate, or assume any values.
Every price, range, change, and percentage you cite must appear verbatim in the data 
provided to you. Double-check your numbers before including them.

POST STRUCTURE (use these exact headings):

## Week in Review
Open with 2-3 sentences that capture the week's overall character. Then include
the weekly performance table. Follow with a paragraph putting the numbers in 
context.

| Metric | Value |
|--------|-------|
| Open | [price] |
| High | [price] |
| Low | [price] |
| Close | [price] |
| Range | [points] |
| Change | [+/- points and %] |

## Day-by-Day Breakdown
Tell the story of each day and how they connected. This shouldn't just repeat 
the table—it should explain how the week unfolded chronologically. Which day 
set the high? The low? How did each session build on the prior?

Include the daily data table as reference, then add narrative context.

## Levels That Mattered
Discuss the key levels from the week: Where did price find support? Where did 
rallies stall? Frame these as observations ("the 5050 level held on three 
separate tests") not as predictions.

## Monthly Context
Discuss where the week's action fits within the broader monthly picture. Did 
we make new monthly highs/lows? Where does the weekly close sit within the 
monthly range?

## Looking Ahead
List the levels that carry forward as reference points. Keep this factual—
state what the levels are and why they're notable from this week's action, 
but don't predict what will happen.

TARGET LENGTH: 600-800 words.

Note: Disclaimer is added automatically by the system.

FORMAT YOUR RESPONSE AS:
---TITLE---
[Compelling title, e.g., "ES Futures Weekly Recap: Consolidation Week Holds Above 5050 as Monthly Highs Tested"]

---CONTENT---
[Full Markdown content with rich narrative]

---META_DESCRIPTION---
[150-160 char description capturing the week's character]
"""
        return prompt
    
    def _build_week_summary(self, context: WeeklyRecapContext) -> str:
        """Build summary of weekly performance."""
        ws = context.weekly_session
        
        parts = [
            f"Open: {ws.open_price}",
            f"High: {ws.high_price}",
            f"Low: {ws.low_price}",
            f"Close: {ws.close_price}",
        ]
        
        # Weekly range
        weekly_range = float(ws.high_price.value) - float(ws.low_price.value)
        parts.append(f"Range: {weekly_range:.2f} points")
        
        # Weekly change
        direction = "higher" if float(ws.change_points) > 0 else "lower"
        parts.append(
            f"Week Change: {abs(float(ws.change_points)):.2f} points {direction} "
            f"({ws.change_percent})"
        )
        
        # Compare to prior week
        if context.prior_week_close:
            prior_close = float(context.prior_week_close.value)
            current_close = float(ws.close_price.value)
            wow_change = current_close - prior_close
            wow_pct = (wow_change / prior_close) * 100
            wow_direction = "above" if wow_change > 0 else "below"
            parts.append(
                f"Week-over-Week: {abs(wow_pct):.2f}% {wow_direction} prior week close"
            )
        
        parts.append(f"Trading Days: {ws.trading_days}")
        parts.append(f"Total Volume: {ws.total_volume:,}")
        
        return "\n".join(f"- {p}" for p in parts)
    
    def _build_daily_breakdown(self, context: WeeklyRecapContext) -> str:
        """Build day-by-day breakdown of the week."""
        rows = []
        
        for session in context.weekly_session.daily_sessions:
            day_name = session.session_date.strftime('%A')
            session_range = float(session.high_price.value) - float(session.low_price.value)
            
            change_str = "N/A"
            if session.change_percent and session.change_points is not None:
                direction = "+" if float(session.change_points) > 0 else ""
                change_str = f"{direction}{session.change_percent}"
            
            rows.append(
                f"| {day_name} | {session.open_price} | {session.high_price} | "
                f"{session.low_price} | {session.close_price} | {change_str} | "
                f"{session_range:.2f} |"
            )
        
        if not rows:
            return "No daily sessions available."
        
        header = "| Day | Open | High | Low | Close | Change | Range |\n"
        header += "|-----|------|------|-----|-------|--------|-------|"
        
        return header + "\n" + "\n".join(rows)
    
    def _build_key_levels(self, context: WeeklyRecapContext) -> str:
        """Build summary of key levels from the week."""
        ws = context.weekly_session
        levels = []
        
        levels.append(f"- Weekly High: {ws.high_price}")
        levels.append(f"- Weekly Low: {ws.low_price}")
        levels.append(f"- Weekly Open: {ws.open_price}")
        levels.append(f"- Weekly Close: {ws.close_price}")
        
        # Calculate mid-point
        mid_point = (float(ws.high_price.value) + float(ws.low_price.value)) / 2
        levels.append(f"- Weekly Mid-Point: {mid_point:.2f}")
        
        return "\n".join(levels)
    
    def _build_monthly_context(self, context: WeeklyRecapContext) -> str:
        """Build monthly context for the weekly recap."""
        parts = []
        
        if context.monthly_high and context.monthly_low:
            monthly_high = float(context.monthly_high.value)
            monthly_low = float(context.monthly_low.value)
            monthly_range = monthly_high - monthly_low
            
            parts.append(
                f"Monthly range: {context.monthly_low} to {context.monthly_high} "
                f"({monthly_range:.2f} points)"
            )
            
            # Where weekly close sits within monthly range
            ws = context.weekly_session
            weekly_close = float(ws.close_price.value)
            
            if monthly_range > 0:
                position_pct = ((weekly_close - monthly_low) / monthly_range) * 100
                parts.append(
                    f"Weekly close at {position_pct:.0f}% of monthly range"
                )
        
        return " ".join(parts) if parts else "Monthly context not available."
    
    def get_system_prompt(self) -> str:
        """Get the system prompt for weekly recap content generation."""
        return """You are a professional futures market analyst writing weekend recaps for a trading blog. Your readers are active futures traders reviewing the week's action and preparing for the week ahead.

YOUR VOICE:
- Write like a weekend desk note from an institutional trading desk
- Reflective and analytical—step back and see the bigger picture
- Professional but engaging—weekends allow for more narrative depth
- Focused on what happened, not what will happen

CORE PRINCIPLES:

1. DATA INTEGRITY: Every fact must come from the provided data. You have daily OHLC 
   data for the entire week—use it to build a coherent narrative.

2. CAPTURE THE WEEK'S CHARACTER: Use the data to describe the week's behavior:
   - Was it trending or consolidating? (compare daily ranges)
   - Was volume front-loaded or back-loaded?
   - Did each day build on the prior, or was there rotation?

3. MEANINGFUL OBSERVATIONS: You CAN and SHOULD make observations that derive from 
   the data:
   - "Three of five sessions closed higher than they opened"
   - "Monday's low held as the week's low despite multiple tests"
   - "The week's range at 85 points was narrower than recent weeks"

4. CONNECT THE DAYS: Don't just list daily stats—show how they relate:
   - "Tuesday's rally attempt stalled at Monday's high"
   - "Wednesday gave back Tuesday's gains, returning to Monday's settlement"
   - "The week closed where it opened, suggesting indecision"

5. AVOID FABRICATION:
   - No predictions about next week
   - No trader psychology or sentiment
   - No news attribution unless specifically provided
   - No "support/resistance held" language (you don't have tick data)

STRUCTURE YOUR CONTENT:
- Open with the week's overall character
- Use tables for reference data
- Connect daily sessions into a narrative
- Provide monthly context and perspective
- Close with factual reference levels for the week ahead

TARGET: 600-800 words of substantive weekend analysis."""


def get_weekly_recap_prompt_builder() -> WeeklyRecapPromptBuilder:
    """Factory function for WeeklyRecapPromptBuilder."""
    return WeeklyRecapPromptBuilder()
