# Generated by Django 5.1.6 on 2025-02-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_blogpost_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="live_demo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
